name: rbdl-toolkit
base: core18
version: 'v0.9-beta'
architectures: [ 'x86' ]
summary: Visualization Toolkit for RBDL models
description: |
  Standalone package for rbdl-toolkit an application for visualizing rigid
  body dynamics models. This tool is mainly used at the robotic research
  group at the university of Heidelberg.

grade: devel
confinement: classic

parts:
  qt513:
    plugin: autotools
    source-type: tar
    source: https://download.qt.io/official_releases/qt/5.13/5.13.2/single/qt-everywhere-src-5.13.2.tar.xz
    install-via: prefix
    build-packages:
      - g++
      - make
      - libassimp-dev
      - libasound2-dev
      - libatspi2.0-dev
      - libcups2-dev
      - libdbus-1-dev
      - libdouble-conversion-dev
      - libdrm-dev
      - libfontconfig1-dev
      - libfreetype6-dev
      - libgbm-dev
      - libgl-dev
      - libgles2-mesa-dev
      - libglib2.0-dev
      - libglu1-mesa-dev
      - libglu-dev
      - libgtk-3-dev
      - libharfbuzz-dev
      - libicu-dev
      - libinput-dev
      - libjpeg-dev
      - libmtdev-dev
      - libnss3-dev
      - libpcre2-dev
      - libpng-dev
      - libpq-dev
      - libproxy-dev
      - libpulse-dev
      - libsqlite3-dev
      - libssl-dev
      - libudev-dev
      - libvulkan-dev
      - libx11-dev
      - libx11-xcb-dev
      - libxcb-glx0-dev
      - libxcb-icccm4-dev
      - libxcb-image0-dev
      - libxcb-keysyms1-dev
      - libxcb-randr0-dev
      - libxcb-render-util0-dev
      - libxcb-render0-dev
      - libxcb-shape0-dev
      - libxcb-shm0-dev
      - libxcb-sync-dev
      - libxcb-xfixes0-dev
      - libxcb-xinerama0-dev
      - libxcb-xinput-dev
      - libxcb-xkb-dev
      - libxcb1-dev
      - libxext-dev
      - libxi-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      - libxrender-dev
      - libegl1-mesa-dev
      - libsystemd-dev
    configflags: [
      "--confirm-license",
      "--opensource",
      "-v",
      "--sysconfdir=/etc/xdg",
      "--openssl-linked",
      "--nomake=examples",
      "--no-rpath",
      "--dbus-linked",
      "--optimized-qmake",
      "--journald",
      "--reduce-relocations",
      "--assimp=system",
      "-qt-xcb",
      "-qt3d-render",
      "-qt3d-logic",
      "-qt3d-animation",
      "-qt3d-input",
      "-qt3d-extras",
      "--qt3d-simd=no"
      ]
    stage-packages:
      - libegl1
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libwayland-server0
      - libxcb-xfixes0
      - libxkbcommon0
      - libxcomposite1
      - libasn1-8-heimdal
      - libasound2
      - libasyncns0
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatspi2.0-0
      - libavahi-client3
      - libavahi-common3
      - libcairo-gobject2
      - libcups2
      - libepoxy0
      - libevdev2
      - libflac8
      - libgssapi3-heimdal
      - libgtk-3-0
      - libgudev-1.0-0
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libice6
      - libinput10
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libmtdev1
      - libpcre2-16-0
      - libpq5
      - libpulse0
      - libroken18-heimdal
      - libsasl2-2
      - libsm6
      - libsndfile1
      - libwacom2
      - libwind0-heimdal
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render-util0
      - libxcb-shape0
      - libxcb-util1
      - libxcb-xinerama0
      - libxcb-xinput0
      - libxcb-xkb1
      - libxcursor1
      - libxi6
      - libxinerama1
      - libxkbcommon-x11-0
      - libxrandr2
      - libassimp4
      - libdouble-conversion1
      - libgl1
      - libglx0
      - libminizip1
      - libxcb-glx0
    after:
      - mesa
  rbdl:
    plugin: cmake
    source-type: git
    source: "https://github.com/ORB-HD/rbdl-orb"
    configflags: [
      "-DCMAKE_BUILD_TYPE=Release",
      "-DRBDL_BUILD_ADDON_LUAMODEL=On",
      "-DRBDL_BUILD_ADDON_URDFREADER=On",
      "-DRBDL_BUILD_ADDON_GEOMETRY=On",
      "-DRBDL_BUILD_PYTHON_WRAPPER=On",
      ]
    build-packages:
      - g++
      - make
      - libunittest++-dev
      - libboost-all-dev
      - lua5.1
      - liblua5.1-0-dev
      - cython3
      - python3-numpy
      - python3-scipy
      - python3-matplotlib
    stage-packages:
      - liblua5.1-0
  rbdl-toolkit:
    plugin: cmake
    source: .
    configflags: [
      "-DCMAKE_BUILD_TYPE=Release",
      "-DTOOLKIT_BUILD_OPTIONAL_PLUGINS=On"
      ]
    after: [ rbdl, qt513, mesa ]
    build-packages:
      - g++
      - make
      - libavcodec-dev
      - libavformat-dev
      - libswresample-dev
      - libswscale-dev
      - libeigen3-dev
      - libassimp-dev
    stage:
      - -usr/lib/x86_64-linux-gnu/dri/i915_dri.so
      - -usr/lib/x86_64-linux-gnu/dri/i965_dri.so
      - -usr/lib/x86_64-linux-gnu/dri/iris_dri.so
      - -usr/lib/x86_64-linux-gnu/dri/kms_swrast_dri.so
      - -usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
      - -usr/lib/x86_64-linux-gnu/dri/nouveau_vieux_dri.so
      - -usr/lib/x86_64-linux-gnu/dri/r200_dri.so
      - -usr/lib/x86_64-linux-gnu/dri/r300_dri.so
      - -usr/lib/x86_64-linux-gnu/dri/r600_dri.so
      - -usr/lib/x86_64-linux-gnu/dri/radeon_dri.so
      - -usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
      - -usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
      - -usr/lib/x86_64-linux-gnu/dri/virtio_gpu_dri.so
      - -usr/lib/x86_64-linux-gnu/dri/vmwgfx_dri.so
      - -usr/lib/x86_64-linux-gnu/libglapi.so.0.0.0
      - -usr/share/doc/libglapi-mesa/changelog.Debian.gz
    stage-packages:
      - libassimp-dev
      - libavcodec57
      - libavformat57
      - libavutil55
      - libbluray2
      - libcairo2
      - libchromaprint1
      - libcroco3
      - libcrystalhd3
      - libdatrie1
      - libdouble-conversion1
      - libdrm2
      - libfontconfig1
      - libfreetype6
      - libgdk-pixbuf2.0-0
      - libgl1
      - libglvnd0
      - libglx0
      - libgme0
      - libgomp1
      - libgraphite2-3
      - libgsm1
      - libharfbuzz0b
      - libicu60
      - liblua5.1-0
      - libmp3lame0
      - libmpg123-0
      - libnuma1
      - libogg0
      - libopenjp2-7
      - libopenmpt0
      - libopus0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpng16-16
      - librsvg2-2
      - libshine3
      - libsnappy1v5
      - libsoxr0
      - libspeex1
      - libssh-gcrypt-4
      - libswresample2
      - libswscale4
      - libthai0
      - libtheora0
      - libtwolame0
      - libva-drm2
      - libva-x11-2
      - libva2
      - libvdpau1
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - libvpx5
      - libwavpack1
      - libwebp6
      - libwebpmux3
      - libx11-6
      - libx264-152
      - libx265-146
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxml2
      - libxrender1
      - libxvidcore4
      - libzvbi0
      - libpcre2-16-0
      - libdri2-1
  mesa:
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri
    build-attributes:
      - no-patchelf # Otherwise snapcraft may strip the build ID and cause the driver to crash
    prime:
      - -lib/udev
      - -usr/doc
      - -usr/doc-base
      - -usr/share/applications
      - -usr/share/apport
      - -usr/share/bug
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/icons
      - -usr/share/libdrm
      - -usr/share/libwacom
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/pkgconfig

apps:
  rbdl-toolkit:
    command: rbdl-toolkit
    environment:
      "LD_LIBRARY_PATH" : "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/mesa:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/mesa-gl:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/xorg"
      "QT_QPA_PLATFORM_PLUGIN_PATH" : "$SNAP/plugins/platforms"
      "QT_PLUGIN_PATH" : "$SNAP/plugins"
      "XKB_CONFIG_ROOT" : "$SNAP/usr/share/X11/xkb"
      "XDG_CONFIG_DIRS" : "$SNAP/etc/xdg:$SNAP/usr/xdg:$XDG_CONFIG_DIRS"
      "XDG_DATA_DIRS" : "$SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS"
      "XDG_DATA_HOME" : "$SNAP_USER_DATA/usr/share"
      "LIBGL_DRIVERS_PATH" : "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri"
      "FONTCONFIG_PATH" : "$SNAP/etc/fonts/config.d"
      "FONTCONFIG_FILE" : "$SNAP/etc/fonts/fonts.conf"
      "TOOLKIT_SEARCHDIR_PATH" : "$SNAP/share/ORB/rbdl-toolkit/"
      "XLOCALEDIR" : "$SNAP/usr/share/X11/locale"
      "LOCPATH" : "$SNAP/usr/lib/locale"
      "XDG_RUNTIME_DIR" : "$XDG_RUNTIME_DIR"
      "APP_DIR" : "$SNAP"
    plugs:
      - opengl
      - x11
      - home
      - desktop
      - desktop-legacy
      - wayland

