name: C/C++ CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
          fetch-depth: 1
    - name: cmake
      run: mkdir build; cd build; cmake ..
    - name: make
      run: make
